#!/bin/bash

function findToken() {
	grep -an "^${1}$" "$0" | head -n 1 | cut -d ':' -f 1
}

function extractData() {
	local BEGIN=$(($(findToken "$1") + 1))
	local END="${2:+$(findToken "$2")}"
	local DATA=$(tail -n +$BEGIN "$0")
	if [[ ! -z "$END" ]] ; then
		DATA=$(echo -n "$DATA" | head -n $(($END - $BEGIN)))
	fi
	echo -n "$DATA" | grep -Ev '^\s*(#.*)?$'
}

#extractData "___SCRIPT_DATA_BEGIN___" "___SCRIPT_DATA_END___"
#echo ---------------
DATA=$(extractData "___SCRIPT_DATA_END___")

echo "$DATA"
IFS=$'\n'
count=1
for i in $DATA ; do 
	echo Line $count
	count=$(($count+1))
	IFS=$' \t\n'
	for j in $i ; do
		echo '>> ' $j
	done
done

exit 0

___SCRIPT_DATA_BEGIN___
   

asd
#qwe This is comment line
zxc
	

___SCRIPT_DATA_END___
zzz		1	a
zzz		2	b
#aaa	3	c
xxx		4  	d

