#!/bin/bash

source my_utils.sh



export a=aaa
#b="bbb\n$a\nccc"
b=$(extractData "===A" "===B")
: '
readarray -t lines <<< "$b"
for i in "${!lines[@]}" ; do
	line="${lines[$i]}"
	echo $(eval echo \"$line\")
done
'

c=$(eval echo \""$b"\")
c=$(evalVariables "$b")
echo "$c"


exit

#c=$(eval echo -e \"$(echo -e "$b")\")
b=$(printf '%b' "$b")
c=$(eval echo -e \"${b}\")
echo -e "$c"

exit

===A
bbb
>> $a <<
ccc
===B


SCRIPT_HOME=$(dirname "$(readlink -fm "$0")")
source "$SCRIPT_HOME/my_tools/my_utils.sh"

#read_cfg '___SCRIPT___' '___END___'
#cfg[qqq]="asd qwe"
#save_cfg '___SCRIPT___' '___END___'

#generate_script_for_save
#DATA=$(make_cfg)
#echo "$DATA"

#execQuiet aaals -la
#is_root && echo root || echo not root

function readScriptSection() {
	start="___SCRIPT___"
	end="___END___"
	
	#extractData $start $end
	
	vals[zzz]="ZZZ"
	echo "${vals[@]}"
	read_cfg $start $end
	cfg[qqq]=QQQ
	a="${cfg[asd]}"
	echo -e "$a"
	#echo "$(($a))"
	a=$(evalVariables "$a")
	echo "$a"
	#save_cfg $start $end
}
readScriptSection

function func1() {
	echo Func 1
	func2
}
	
function func2() {
	echo Func 2
	func3
}

function func3() {
	echo Func 3
	func4
}

function func4() {
	echo Func 4
	ggetStack
}

#func1

#echo $EUID

exit

___SCRIPT___
 asd = Some \t da"ta "${vals[@]}" "$(pwd)" \n qqqqq
   qwe = Some = data
az=az

___END___
eeee=aaa
