#!/bin/bash

source my_utils.sh

#read_cfg '___SCRIPT___' '___END___'
#cfg[qqq]="asd qwe"
#save_cfg '___SCRIPT___' '___END___'

#generate_script_for_save
#DATA=$(make_cfg)
#echo "$DATA"


declare -A c
# To make new escape codes use: printf "%q\n" "$(tput setaf 1)"
# Use "man tput" and "man terminfo" to get parameters for tput
c[black]=$'\E[30m'
c[red]=$'\E[31m'
c[green]=$'\E[32m'
c[yellow]=$'\E[33m'
c[blue]=$'\E[34m'
c[magenta]=$'\E[35m'
c[cyan]=$'\E[36m'
c[white]=$'\E[37m'
c[reset]=$'\E(B\E[m'

#echo "This is ${c[red]}important${c[white]} text."

COL1=$(tput setaf 5)$(tput setab 3)
COL2=$(tput sgr0)
echo "This is ${COL1}important${COL2} text."

exit

___SCRIPT___
 asd = Some \t data "${vals[@]}"
   qwe = Some = data  

___END___
eeee
