#!/bin/bash

SCRIPT_HOME=$(dirname "$(readlink -fm "$0")")

. "$SCRIPT_HOME/my_tools/my_utils.sh"

function fileInfo() {
	local s=$(stat --printf "%s\t%Y" "$1")
	local n=$(basename "$1")
	local d=$(dirname "$1")
	echo -e "$s\t$d\t$n"
}

function listFiles() {
	(find . -type f -iname "${1:-*}") |
	(while IFS=$'\n' read -a i ; do
		fileInfo "$i"
	done)
}

function importFileList() {
	sqlite3 "$fdb" <<- EOF
		.bail on
		
		create table f (
			fsize numeric(15),
			ftime numeric(15),
			fdir varchar(100),
			fname varchar(100)
		);

		.separator "\t"
		.import "${fou}" f
	EOF
}

fou=$(mktemp -p "$XDG_RUNTIME_DIR" files-XXXXXX.txt)
fdb="$XDG_RUNTIME_DIR/fdb.sqlite"

listFiles > "$fou"
importFileList
#cat "$fou"

rm -f "$fou"
echo "Done."
