#!/bin/bash

SCRIPT_HOME=`realpath "${0}"`
SCRIPT_HOME=`dirname "$SCRIPT_HOME"`

. "$SCRIPT_HOME/my_utils.sh"
#. "$SCRIPT_HOME/bashlib/bsfl.sh"

LOG_FILE=/dev/tty

#msg_status "Hello world" "OK"
log you are not root
#echo "$(date -R): asd"
