package com.improc;

public class TestClass {

	public static void main(String[] args) {
		// Notepad has added this line and removed the autogenerated TODO: above
		// Edited again with notepad
		System.out.println("I already made some changes in the repository");	
		// Added from notepad
		// Edited in eclipse
	}

}
