package com.improc;

public class TestClass {

	public static void main(String[] args) {
		// Notepad has added this line and removed the autogenerated TODO: above
		System.out.println("I already made some changes in the repository");	
	}

}
