# Format: xml, json, yml
format: json

before: |                   # Velocity macto
    truncate table testdata1;
    truncate table testdata1;

after: |                   # Velocity macto
    begin
        exec_stored_procedure;
    end

defs:
    -   # Comment
        name: Location          # Just a name
        path: /locations/\d+    # RegRex to math against record path
        before:                 # Velocity macto
            truncate table testdata
        after:                  # Velocity macto
            begin
                exec_stored_procedure;
            end
        sql: |                  # Velocity macto
            insert into testdata
                (data1, data2, data3)
            values
                (?,?,?)
        params:                 # SQL parameters formatting
        - |                     # Velocity macto
            A value $rec._LINE
        - $rec._PARENT._PARENT._ID
        - $su.abbreviate($rec.classes, 10)

    -   # Comment
        name: Patterns
        path: /destinations/[^/]*/patterns
